# Load the Dataset
This step imports the required libraries and loads the product recommendation dataset into a Pandas DataFrame.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("../data/amazon-product-reviews-dataset.csv")

# View the First Five Rows
This step displays the first five rows of the dataset to understand its structure.

In [2]:
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

# Dataset Dimensions
This step displays the number of rows and columns in the the dataset.

In [3]:
df.shape

(1597, 27)

# Explore the Dataset
This step provides an overview of the dataset, including column names, data types, and summary statistics.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1597 entries, 0 to 1596
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1597 non-null   object
 1   asins                 1597 non-null   object
 2   brand                 1597 non-null   object
 3   categories            1597 non-null   object
 4   colors                774 non-null    object
 5   dateAdded             1597 non-null   object
 6   dateUpdated           1597 non-null   object
 7   dimension             565 non-null    object
 8   ean                   898 non-null    float64
 9   keys                  1597 non-null   object
 10  manufacturer          965 non-null    object
 11  manufacturerNumber    902 non-null    object
 12  name                  1597 non-null   object
 13  prices                1597 non-null   object
 14  reviews.date          1217 non-null   object
 15  reviews.doRecommend   539 non-null    object
 16  reviews.numHelpful    900 non-null    float64
 17  reviews.rating        1177 non-null   float64
 18  reviews.sourceURLs    1597 non-null   object
 19  reviews.text          1597 non-null   object
 20  reviews.title         1580 non-null   object
 21  reviews.userCity      0 non-null      float64
 22  reviews.userProvince  0 non-null      float64
 23  reviews.username      1580 non-null   object
 24  sizes                 0 non-null      float64
 25  upc                   898 non-null    float64
 26  weight                686 non-null    object
dtypes: float64(7), object(20)
memory usage: 337.0+ KB

In [5]:
df.describe()

,ean,reviews.numHelpful,reviews.rating,reviews.userCity,reviews.userProvince,sizes,upc
count,8.980000e+02,900.000000,1177.000000,0.0,0.0,0.0,8.980000e+02
mean,8.443135e+11,83.584444,4.359388,NaN,NaN,NaN,8.443135e+11
std,3.416444e+09,197.150238,1.021445,NaN,NaN,NaN,3.416444e+09
min,8.416670e+11,0.000000,1.000000,NaN,NaN,NaN,8.416670e+11
25%,8.416670e+11,0.000000,4.000000,NaN,NaN,NaN,8.416670e+11
50%,8.416670e+11,0.000000,5.000000,NaN,NaN,NaN,8.416670e+11
75%,8.487190e+11,34.000000,5.000000,NaN,NaN,NaN,8.487190e+11
max,8.487190e+11,997.000000,5.000000,NaN,NaN,NaN,8.487190e+11

# Check for Missing Values
This step identifies missing values in each column of the dataset.

In [6]:
df.isnull().sum()

id                         0
asins                      0
brand                      0
categories                 0
colors                   823
dateAdded                  0
dateUpdated                0
dimension               1032
ean                      699
keys                       0
manufacturer             632
manufacturerNumber       695
name                       0
prices                     0
reviews.date             380
reviews.doRecommend     1058
reviews.numHelpful       697
reviews.rating           420
reviews.sourceURLs         0
reviews.text               0
reviews.title             17
reviews.userCity        1597
reviews.userProvince    1597
reviews.username          17
sizes                   1597
upc                      699
weight                   911
dtype: int64

# Check for Duplicate Records
This step checks whether the dataset contains duplicate rows.

In [7]:
df.duplicated().sum()

np.int64(0)

# View Column Names
This step displays the names of all columns in the dataset.

In [8]:
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

# Display a Random Sample
This step displays a random sample of rows from the dataset.

In [9]:
df.sample(5, random_state=42)

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
802,AVpe7LD5LJeJML43ybWA,"B00DOPNO4M,B00BWYQ9YE,B00CYQPMJC,B00CUU1CGY,B0...",Amazon,"Amazon Devices,Kindle Store,buy a kindle",NaN,2015-05-22T15:33:59Z,2017-07-18T23:52:40Z,NaN,NaN,"kindlefirehdx7/b00dopno4m,kindlefirehdx7/b00bw...",...,NaN,http://www.amazon.com/kindle-fire-hdx-student-...,I love this handheld device especially all the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,AVpfpzCi1cnluZ0-oxEr,B00DOPNLJ0,Amazon,Amazon Devices,NaN,2015-06-02T08:44:19Z,2017-08-07T15:41:59Z,NaN,NaN,kindlefirehdx89/b00dopnlj0,...,NaN,http://www.amazon.com/Kindle-Fire-HDX-Display-...,Updated 12/8/2014One year in...This review is ...,KF HDX 8.9 is ok do homework on Prime download...,NaN,NaN,B. Tarbuck,NaN,NaN,NaN
350,AVpfLiCSilAPnD_xWpk_,B00CX5P8FC,Amazon,"Categories,Amazon Devices,Electronics Features...",NaN,2015-05-22T18:12:20Z,2017-08-08T22:03:26Z,NaN,8.487190e+11,"848719022827,0848719022827,amazonfiretv/b00cx5...",...,NaN,http://www.amazon.com/Fire-TV-streaming-media-...,This was easy to set up I can access many movi...,Amazon Fire TV - A must have!!!!,NaN,NaN,Amazon Customer,NaN,8.487190e+11,NaN
682,AVzRlo37glJLPUi8FbPy,B01LW1MS9C,Amazon,"Amazon Devices,Kindle Store",NaN,2017-06-22T20:55:23Z,2017-08-13T08:28:46Z,NaN,NaN,amazonechodotcasefitsechodot2ndgenerationonlyc...,...,5.0,https://www.amazon.com/Amazon-Echo-Case-fits-G...,I am thoroughly impressed with my Echo Dot and...,The Extra Touch,NaN,NaN,dm,NaN,NaN,NaN
1324,AVpfpK8KLJeJML43BCuD,B01BH83OOM,Amazon,"Amazon Devices,Home,Smart Home & Connected Liv...",Black,2017-01-04T03:51:17Z,2017-08-13T08:31:07Z,4.8 in x 6.6 in x 3.2 in,8.416670e+11,amazontapalexaenabledportablebluetoothspeaker/...,...,5.0,http://reviews.bestbuy.com/3545/5097300/review...,Great little device easy to connect to bluetoo...,Easy small decent sound,NaN,NaN,Drjim,NaN,8.416670e+11,1.75 lbs

# Check Unique Values
This step checks the number of unique values in each column.

In [10]:
df.nunique()

id                        66
asins                     54
brand                      2
categories                19
colors                     3
dateAdded                 50
dateUpdated               42
dimension                  2
ean                        2
keys                      66
manufacturer               2
manufacturerNumber         6
name                      62
prices                    66
reviews.date             382
reviews.doRecommend        2
reviews.numHelpful       182
reviews.rating             5
reviews.sourceURLs       499
reviews.text            1048
reviews.title           1270
reviews.userCity           0
reviews.userProvince       0
reviews.username         949
sizes                      0
upc                        2
weight                     9
dtype: int64

# Inspect Columns Names
This step identifies the columns that will be used to build the recommendation system.

In [11]:
print(df.columns.tolist())

['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded', 'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer', 'manufacturerNumber', 'name', 'prices', 'reviews.date', 'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs', 'reviews.text', 'reviews.title', 'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes', 'upc', 'weight']

# Check Data Types
This step verifies the data type of each column.

In [12]:
df.dtypes

id                       object
asins                    object
brand                    object
categories               object
colors                   object
dateAdded                object
dateUpdated              object
dimension                object
ean                     float64
keys                     object
manufacturer             object
manufacturerNumber       object
name                     object
prices                   object
reviews.date             object
reviews.doRecommend      object
reviews.numHelpful      float64
reviews.rating          float64
reviews.sourceURLs       object
reviews.text             object
reviews.title            object
reviews.userCity        float64
reviews.userProvince    float64
reviews.username         object
sizes                   float64
upc                     float64
weight                   object
dtype: object

# Select Required Columns
This step selects the columns required for building the product recommendation system.

In [13]:
recommendation_df = df[["reviews.username", "name", "reviews.rating"]]
recommendation_df.head()

     reviews.username               name  reviews.rating
0          Cristina M  Kindle Paperwhite             5.0
1               Ricky  Kindle Paperwhite             5.0
2       Tedd Gardiner  Kindle Paperwhite             4.0
3              Dougal  Kindle Paperwhite             5.0
4  Miljan David Tanic  Kindle Paperwhite             5.0

# Check for missing Values
This step checks missing values in the selected columns.

In [14]:
recommendation_df.isnull().sum()

reviews.username     17
name                  0
reviews.rating      420
dtype: int64

# Remove Missing Values
This step removes rows containing missing values from the selected columns.

In [15]:
recommendation_df = recommendation_df.dropna()
recommendation_df.head()

     reviews.username               name  reviews.rating
0          Cristina M  Kindle Paperwhite             5.0
1               Ricky  Kindle Paperwhite             5.0
2       Tedd Gardiner  Kindle Paperwhite             4.0
3              Dougal  Kindle Paperwhite             5.0
4  Miljan David Tanic  Kindle Paperwhite             5.0

# Rename Columns
This step renames the columns to simpler names for easier analysis.

In [16]:
recommendation_df.columns = ["user", "product", "rating"]
recommendation_df.head()

                 user            product  rating
0          Cristina M  Kindle Paperwhite     5.0
1               Ricky  Kindle Paperwhite     5.0
2       Tedd Gardiner  Kindle Paperwhite     4.0
3              Dougal  Kindle Paperwhite     5.0
4  Miljan David Tanic  Kindle Paperwhite     5.0

# Create User-Product Matrix
This step creates a matrix where rows represent users, columns represent products, and values represent ratings.

In [17]:
user_product_matrix = recommendation_df.pivot_table(
    index="user",
    columns="product",
    values="rating"
)

user_product_matrix.head()

product,Alexa Voice Remote for Amazon Echo and Echo Dot,Alexa Voice Remote for Amazon Fire TV and Fire TV Stick,All-New Amazon Fire 7 Tablet Case (7th Generation,All-New Amazon Fire HD 8 Tablet Case (7th Generation,All-New Amazon Fire TV Game Controller,All-New Amazon Kid-Proof Case for Amazon Fire 7 Tablet (7th Generation,All-New Amazon Kid-Proof Case for Amazon Fire HD 8 Tablet (7th Generation,All-New Fire 7 Kids Edition Tablet,All-New Fire 7 Tablet with Alexa,All-New Fire HD 8 Kids Edition Tablet,...,Kindle Keyboard,Kindle Oasis E-reader with Leather Charging Cover - Walnut,Kindle Oasis with Leather Charging Cover - Black,Kindle Paperwhite,Kindle Paperwhite 3G,Kindle Paperwhite E-reader - Black,Kindle Voyage E-reader,Kindle for Kids Bundle with the latest Kindle E-reader,Moshi Anti-Glare No Bubble Screen Protector for the Fire Phone,Replacement Remote for Amazon Fire TV Stick
user,,,,,,,,,,,,,,,,,,,,,
1-Apr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1soni,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25Firefighter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Fill Missing Ratings
This step replaces missing ratings with 0 to prepare the data for recommendation.

In [18]:
user_product_matrix = user_product_matrix.fillna(0)

user_product_matrix.head()

product,Alexa Voice Remote for Amazon Echo and Echo Dot,Alexa Voice Remote for Amazon Fire TV and Fire TV Stick,All-New Amazon Fire 7 Tablet Case (7th Generation,All-New Amazon Fire HD 8 Tablet Case (7th Generation,All-New Amazon Fire TV Game Controller,All-New Amazon Kid-Proof Case for Amazon Fire 7 Tablet (7th Generation,All-New Amazon Kid-Proof Case for Amazon Fire HD 8 Tablet (7th Generation,All-New Fire 7 Kids Edition Tablet,All-New Fire 7 Tablet with Alexa,All-New Fire HD 8 Kids Edition Tablet,...,Kindle Keyboard,Kindle Oasis E-reader with Leather Charging Cover - Walnut,Kindle Oasis with Leather Charging Cover - Black,Kindle Paperwhite,Kindle Paperwhite 3G,Kindle Paperwhite E-reader - Black,Kindle Voyage E-reader,Kindle for Kids Bundle with the latest Kindle E-reader,Moshi Anti-Glare No Bubble Screen Protector for the Fire Phone,Replacement Remote for Amazon Fire TV Stick
user,,,,,,,,,,,,,,,,,,,,,
1-Apr,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1215,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1234,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1soni,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25Firefighter,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Display Matrix Dimensions
This step displays the number of users and products in the recommendation matrix.

In [19]:
user_product_matrix.shape

(836, 62)

# Calculate User Similarity
This step calculates the similarity between users based on their product ratings.

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

user_similarity = cosine_similarity(user_product_matrix)

user_similarity.shape

(836, 836)

# Convert User Similarity Matrix to DataFrame
This step converts the user similarity matrix into a DataFrame for easier interpretation.

In [21]:
user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_product_matrix.index,
    columns=user_product_matrix.index
)

user_similarity_df.head()

user,1-Apr,1215,1234,1soni,25Firefighter,5bros,7011,A. Dent Aragorn,A. Younan,A.C,...,toeka,ts120,txtech1997,unplug,vishal,wadas1989,wax0pal,william lombardo,wirelesssassyowner,zman
user,,,,,,,,,,,,,,,,,,,,,
1-Apr,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1215,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1234,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1soni,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
25Firefighter,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

# Find Similar Users
This step displays the users most similar to a selected user.

In [22]:
sample_user = user_similarity_df.index[0]

user_similarity_df[sample_user].sort_values(ascending=False).head(10)

user
wirelesssassyowner    1.0
1-Apr                 1.0
1215                  1.0
str4920               1.0
sta123                1.0
sparkles              1.0
smvere                1.0
shar555               1.0
shaithus              1.0
samboo                1.0
Name: 1-Apr, dtype: float64

# Find Top Rated Products
This step identifies the highest-rated products in thr dataset.

In [23]:
top_products = (
    recommendation_df.groupby("product")["rating"]
    .mean()
    .sort_values(ascending=False)
)

top_products.head(10)

product
All-New Fire HD 8 Kids Edition Tablet                                        5.000000
All-New Amazon Kid-Proof Case for Amazon Fire HD 8 Tablet (7th Generation    5.000000
Amazon Echo - Black                                                          5.000000
Fire HD 6 Tablet                                                             5.000000
Fire HD 7 Tablet                                                             5.000000
Certified Refurbished Kindle Paperwhite E-reader - Black                     5.000000
Kindle E-reader - Black                                                      5.000000
Kindle Paperwhite E-reader - Black                                           5.000000
Kindle Paperwhite 3G                                                         5.000000
Certified Refurbished Echo Dot (2nd Generation) - Black                      4.833333
Name: rating, dtype: float64

# Recommend Products for a User
This step recommends products based on the ratings of similar users.

In [24]:
sample_user = recommendation_df["user"].iloc[0]

rated_products = recommendation_df[
    recommendation_df["user"] ==sample_user
]["product"]

recommended_products = top_products[~top_products.index.isin(rated_products)]

recommended_products.head(10)

product
All-New Fire HD 8 Kids Edition Tablet                                        5.000000
All-New Amazon Kid-Proof Case for Amazon Fire HD 8 Tablet (7th Generation    5.000000
Amazon Echo - Black                                                          5.000000
Fire HD 6 Tablet                                                             5.000000
Fire HD 7 Tablet                                                             5.000000
Certified Refurbished Kindle Paperwhite E-reader - Black                     5.000000
Kindle E-reader - Black                                                      5.000000
Kindle Paperwhite E-reader - Black                                           5.000000
Kindle Paperwhite 3G                                                         5.000000
Certified Refurbished Echo Dot (2nd Generation) - Black                      4.833333
Name: rating, dtype: float64

# Save Recommendations
This step saves the recommended products to a CSV file.

In [25]:
recommended_products.head(10).to_csv("../models/recommended_products.csv")

# Project Summary
This project built a basic product recommendation system using user ratings and cosine similarity. It identified similar users and recommended highly rated products that the selected user had not yet rated.